version: '3'

services:
  php:
    build:
      context: ./tools/images/php
    volumes:
      - .:/var/www/html

  apache:
    image: httpd:alpine
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./public:/var/www/html/public
      - ./tools/httpd/localhost.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./tools/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
networks:
  default:
    external:
      name: postfix_admin_default