version: '3'

services:
  php:
    build:
      context: ./tools/images/php
    volumes:
      - .:/var/www/html
    user: ${CURRENT_UID}

  apache:
    image: httpd:alpine
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./public:/var/www/html/public
      - ./tools/httpd/localhost.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./tools/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
  yarn:
    image: node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: /bin/sh -c "npm install && yarn encore dev-server"
    user: ${CURRENT_UID}
networks:
  default:
    external:
      name: postfix_admin_default