version: '3'

services:
  php:
    build:
      context: ./tools/images/php
    volumes:
      - .:/var/www/html
    user: ${CURRENT_UID}
  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./public:/var/www/html/public
      - ./tools/nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
  yarn:
    image: node
    working_dir: /var/www
    ports:
      - 3000:3000
    volumes:
      - .:/var/www
    command: /bin/sh -c "yarn && yarn dev"

volumes:
  db_data:
    driver: local
networks:
  default:
    external:
      name: postfix_admin_default