version: '3'

services:
  php:
    image: ghcr.io/miithrandiir/postfix_admin
    volumes:
      - .:/var/www/html
    user: ${CURRENT_UID}
  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./public:/var/www/html/public
      - ./tools/nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
  yarn:
    image: node
    working_dir: /var/www
    ports:
      - 3000:3000
    volumes:
      - .:/var/www
    command: /bin/sh -c "yarn && yarn dev"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: postfix
      MYSQL_DATABASE: postfix
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db_data:
    driver: local