name: Tests
on: [ push ]
jobs:
  CheckSecurity:
    name: Symfony Check Security
    runs-on: ubuntu-latest
    container: ghcr.io/miithrandiir/postfix_admin:latest
    steps:
      - uses: actions/checkout@v2
      - name: security:check
        run: symfony security:check
  lint:
    name: lint
    runs-on: ubuntu-latest
    container: ghcr.io/miithrandiir/postfix_admin:latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress
      - name: Lint
        run: make lint
  yarn:
    name: yarn
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install --ignore-engines
      - name: Build
        run: yarn build
      - name: Linter
        run: yarn lint